{{- if .Values.teamRoles.committer.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: committer
  labels:
    jenkins.io/kind: "EnvironmentRole"
  annotations:
    title: "Committer"
    description: "A committer can write to project resources but cannot add/remove users"
{{ if .Values.teamRoles.committer.rules -}}
rules:
{{ toYaml .Values.teamRoles.committer.rules | indent 0 }}
{{- end }}
{{- end }}
