{{- if .Values.teamRoles.owner.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: owner
  labels:
    jenkins.io/kind: "EnvironmentRole"
  annotations:
     title: "Team Owner"
     description: "A team owner can add/remove users and has write access to all team resources"
{{ if .Values.teamRoles.owner.rules -}}
rules:
{{ toYaml .Values.teamRoles.owner.rules | indent 0 }}
{{- end }}
{{- end }}
