{{- if .Values.teamRoles.viewer.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: viewer
  labels:
    jenkins.io/kind: "EnvironmentRole"
  annotations:
     title: "Viewer"
     description: "A viewer can view all project resources"
{{ if .Values.teamRoles.viewer.rules -}}
rules:
{{ toYaml .Values.teamRoles.viewer.rules | indent 0 }}
{{- end }}
{{- end }}
