dependencies:
- condition: jenkins.enabled
  name: jenkins
  repository: https://charts.helm.sh/stable
  version: 1.9.5 
- alias: expose
  condition: expose.enabled
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.111
- alias: cleanup
  condition: cleanup.enabled
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.111
- condition: chartmuseum.enabled
  name: chartmuseum
  repository: http://chartmuseum.jenkins-x.io
  version: 1.1.7
- condition: nexus.enabled
  name: nexus
  repository: http://chartmuseum.jenkins-x.io
  version: 0.1.37
- condition: docker-registry.enabled
  name: docker-registry
  repository: https://charts.helm.sh/stable
  version: 1.9.3
- alias: gcactivities
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.1.155
- alias: gcpods
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.1.155
- alias: gcpreviews
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.1.155
- alias: controllerbuild
  condition: controllerbuild.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.1.155
- alias: controllerrole
  condition: controllerrole.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.1.155
- alias: postinstalljob
  condition: postinstalljob.enabled
  name: jx
  repository: http://chartmuseum.jenkins-x.io
  version: 2.1.155
